# Generated by Django 5.2.3 on 2025-06-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['source_text', 'source_language', 'target_language'], name='api_transla_source__15e690_idx'), models.Index(fields=['last_accessed'], name='api_transla_last_ac_ecebd0_idx')],
                'unique_together': {('source_text', 'source_language', 'target_language')},
            },
        ),
    ]
