# Generated by Django 5.2.3 on 2025-06-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_cached', models.BooleanField(default=False)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='api.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_usertra_user_id_9df1b5_idx'), models.Index(fields=['timestamp'], name='api_usertra_timesta_03b67d_idx')],
            },
        ),
    ]
