# Generated by Django 5.2.3 on 2025-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usertranslationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertranslationhistory',
            name='translation',
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='input_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='output_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='source_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='target_language',
            field=models.CharField(default='es', max_length=10),
        ),
    ]
