# Generated by Django 5.2.3 on 2025-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usertranslationhistory_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved to access the system.'),
        ),
    ]
