# Generated by Django 5.2.3 on 2025-06-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('source_text', 'source_language', 'target_language', 'translated_text')},
        ),
    ]
